# Generated by Django 6.0.6 on 2026-07-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apunte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "formato",
                    models.CharField(
                        choices=[("MD", "Markdown"), ("RST", "ReStructuredText")],
                        default="MD",
                        max_length=5,
                        verbose_name="Formato de Texto",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("NO_EMPEZADO", "No empezado"),
                            ("EN_PROGRESO", "En progreso"),
                            ("COMPLETADO", "Completado"),
                        ],
                        default="NO_EMPEZADO",
                        max_length=15,
                        verbose_name="Estado de Estudio",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Apunte",
                "verbose_name_plural": "Apuntes",
                "ordering": ["-fecha_actualizacion"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familias",
                        to="gestion.categoria",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Familia / Subcategoría",
                "verbose_name_plural": "Familias / Subcategorías",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ImagenApunte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="apuntes_imagenes/", verbose_name="Imagen"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Descripción / Alt Text",
                    ),
                ),
                (
                    "apunte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="gestion.apunte",
                        verbose_name="Apunte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Apunte",
                "verbose_name_plural": "Imágenes de Apunte",
            },
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temas",
                        to="gestion.familia",
                        verbose_name="Familia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "Temas",
                "ordering": ["familia", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="apunte",
            name="tema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apuntes",
                to="gestion.tema",
                verbose_name="Tema",
            ),
        ),
    ]
