# Generated by Django 6.0.6 on 2026-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=60, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="apunte",
            name="favorito",
            field=models.BooleanField(default=False, verbose_name="Favorito"),
        ),
        migrations.AddField(
            model_name="apunte",
            name="relacionado_a",
            field=models.ManyToManyField(
                blank=True, to="gestion.apunte", verbose_name="Apuntes Relacionados"
            ),
        ),
        migrations.AddField(
            model_name="apunte",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="apuntes",
                to="gestion.tag",
                verbose_name="Etiquetas",
            ),
        ),
    ]
